# Generated by Django 3.2.13 on 2022-04-24 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Category',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='course.category'),
        ),
    ]
